name = "greet"
description = "Filoject example application"
version = "0.1.0-dev"

authors = ["René Hartmann"]
maintainers = ["René Hartmann <rhartmann@users.sourceforge.net>"]
maintainers-logins = ["rehartmann"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["greet"]

[[depends-on]]
filoject = "*"

[[pins]]
filoject = { path = "../.." }
